### PR TITLE
Delete the use of the non-extisting class Twig_Autoloader for Twig 2.X

### PR DESCRIPTION
**Pull request by atalargo**
Set compatibility with Twig 2.X

### CODE REVIEW

**Review by laurentbardin — APPROVED** [review]

**Comment by laurentbardin** [comment]
I can't merge this as I don't have write access on this repo. 😢

**Comment by masterzen** [comment]
@laurentbardin you can now.

**Comment by laurentbardin** [comment]
@masterzen Awesome.

**Comment by laurentbardin** [comment]
I can't delete the branch, I NEED MORE ACCESS!

**Pull request merged**
